- name: Import GoLang from common role
  ansible.builtin.include_role:
    name: common
    tasks_from: golang

    

- name: Load Master Data
  ansible.builtin.shell: mysql -h 10.0.0.5 -u root -pRoboShop@1 {{component_name}} < db/master-data.sql
  args:
    chdir: /app
